### PR TITLE
setup cypress and add one integration test

### PR DESCRIPTION
**Pull request by mhadaily**
Hi, 
This must fix this issue https://github.com/ritz078/raaga/issues/68

I have also written one test for you, run `yarn test:e2e` and then run all tests, you'll see all tests passes.

### CODE REVIEW

**Comment by ankeetmaini** [comment]
Can you add support for writing tests in TS? This [link](https://docs.cypress.io/guides/tooling/typescript-support.html#Transpiling-TypeScript-test-files) should help.

**Comment by mhadaily** [comment]
@ankeetmaini fixed.

**Comment by ankeetmaini** [comment]
@mhadaily This looks great! 

Just one more thing, will these TS test files be preprocessed by Cypress if I use modern ES6 syntax like `import` and stuff to import custom commands?

I'm not sure if they will pass via Webpack/build pipeline as I don't see how Cypress will hook into it. Can you try importing a util and see if it works correctly?

cc: @ritz078

**Comment by ritz078** [comment]
Thanks for your contribution @mhadaily .

Currently, this PR will always run on https://raaga.io. But the problem is that it won't serve any purpose if it runs on the master branch's code. It should run on the current branch code. Here is the flow that I was thinking about:

- Each branch gets deployed to a URL (already supported using zeit)
- We use that URL and run e2e tests on that.

Things to figure out:
- how to programmatically access now's URL in a PR run tests on it. See https://zeit.co/docs/v2/advanced/now-for-github#extending-your-github-workflow and https://developer.github.com/v3/repos/deployments/

Where do we do it:
We will use GitHub Actions for that.

Let me know if this makes sense and if something is not clear. Also tell me what all access you will need. I guess I can make a team on [now](https://zeit.co/dashboard) and that should be enough.

**Suggestions?**
Also, what do you think about cypress? One argument I have heard against cypress is that it is slow. I have to test an app that requires high performance and since cypress runs inside browser, it might cause main thread blocking issues. Should we go for something like [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) ?

**Comment by ritz078** [comment]
Update: going ahead with cypress for now.

**Comment by mhadaily** [comment]
@ritz078 should I continue on the PR or what?

**Comment by ritz078** [comment]
@mhadaily yes. please continue on the PR. 🙂

**Comment by mhadaily** [comment]
I am not sure if I can continue on it. please apparently I need to get access to the repo and https://zeit.co/ritz078/synth/jyy6t3ul1 where I can see all different deployment and etc. 

I think this is not something you want to share though. I suggest if this implementation works well. with default URL, you either merge it and continue to open a new issue and let someone who has proper access fix it. or someone needs to help me to push more commit to this branch and gimme the URL.  

What's your suggestions?

**Comment by ritz078** [comment]
I was just exploring the possibility of creating a team on zeit. The problem is that I personally have a free unlimited account but if I create a team, it will be a free account that won't support custom domain names. So I can't create that. I will have to figure out a way to fix this as in the long run I want to create a team but for now I will merge this PR.

**Comment by ritz078** [comment]
@all-contributors please add @mhadaily for code.

**Comment by ritz078** [comment]
@all-contributors please add @mhadaily for code.

**Review by ritz078 — APPROVED** [review]

**Comment by ritz078** [comment]
Thank you for your contribution 🎉

**Pull request merged**
